name: Build

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  push:
    branches: [ "main" ]

defaults:
  run:
    shell: bash -ileo pipefail {0}

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container:
      image: oraclelinux:9

    services:
      runtime:
        image: oraclelinux:9
        options: --privileged --name runtime --hostname runtime --workdir /workspace --entrypoint /usr/sbin/init
        volumes:
          - ${{ github.workspace }}:/workspace/

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: Install tmate
        run: |
          yum-config-manager --add-repo https://download.docker.com/linux/rhel/docker-ce.repo
          yum install -y epel-release
          yum install -y tmate docker-ce-cli

      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
        with:
          install-dependencies: false
