name: Build

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  push:
    branches: [ "main" ]

defaults:
  run:
    shell: bash -ileo pipefail {0}

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/wangzw/devel:latest
      options: --privileged

    services:
      segment1:
        image: oraclelinux:9
        options: --privileged --name segment1 --hostname segment1 --workdir /workspace --entrypoint /usr/sbin/init
        volumes:
          - ${{ github.workspace }}:/workspace/
      segment2:
        image: oraclelinux:9
        options: --privileged --name segment2 --hostname segment2 --workdir /workspace --entrypoint /usr/sbin/init
        volumes:
          - ${{ github.workspace }}:/workspace/
      segment3:
        image: oraclelinux:9
        options: --privileged --name segment3 --hostname segment3 --workdir /workspace --entrypoint /usr/sbin/init
        volumes:
          - ${{ github.workspace }}:/workspace/

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: Install tmate & docker-ce-cli
        run: |
          set -x
          
          yum-config-manager --add-repo https://download.docker.com/linux/rhel/docker-ce.repo
          yum install -y epel-release docker-ce-cli
          yum install -y tmate

      - name: Setup authorized ssh
        run: |
          docker cp ~/.ssh/id_rsa.pub segment1:/root/.ssh/authorized_keys
          docker cp ~/.ssh/id_rsa.pub segment2:/root/.ssh/authorized_keys
          docker cp ~/.ssh/id_rsa.pub segment3:/root/.ssh/authorized_keys
          
          /usr/bin/start-systemd.sh

      - name: Setup tmate session
        uses: lhotari/action-upterm@v1
